### ISSUE TITLE
Enhancement: Ability to add item to shopping list even when it’s not known

### ISSUE THREAD

**Issue by superpower10** [supergeorg/Grocy-SwiftUI#153] opened 2023-02-24 08:50 UTC
Sometimes I quickly want to add an item to the shopping list which is not in „Master data - Products“. 

But at the moment it’s not possible. Please change it like it is in the Web GUI.

**Comment by supergeorg** [comment] 2023-02-24 18:55
This is a duplicate of issue #135

**Closed by supergeorg** 2023-02-24 18:55 UTC
